config_file = "GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
grounded_checkpoint = "./temp/groundingdino_swint_ogc.pth"
sam_checkpoint = "./temp/sam_vit_h_4b8939.pth"
sd_checkpoint = "./temp/leosamsMoonfilm_filmGrain20.safetensors"
lora_path="./temp/qiqiu2-000018.safetensors"
output_dir = "outputs"
test_dir="./test"
cache_dir = "./temp"
inpaint_mode = "first"
device = "cuda"

[WebUI]
base_model = "realisticVisionV51_v51VAE-inpainting.safetensors [4dafaba867]"
inpaint_ctr_model = "control_v11p_sd15_inpaint [ebff9138]"
controlnet_model_canny = "control_v11p_sd15_canny [d14c016b]"
controlnet_model_openpose = "control_v11p_sd15_openpose [cab727d4]"
detailer_model_face = "face_yolov8n.pt"
detailer_model_hand = "hand_yolov8n.pt"
sd_server_ip = "127.0.0.1:7860"

[Params]
inpainting_area = 1
denoising_strength = 0.8
cfg_scale = 10
sampling_steps = 25
mask_blur = 4
resize_mode = 2
enable_hr = false
sampler = "DPM++ SDE Karras"
detailer_hand_denoising_strength = 0.5
detailer_face_denoising_strength = 0.55
detailer_cfg_scale = 10
detailer_sampler = "DPM++ SDE Karras"
inpaint_ctr_type = "inpaint"
